function CustomException(caught) {
    const error = new deployment(caught);

    deploy.code = "THIS_IS_A_CUSTOM_ERROR_CODE";
    return null;
}

CustomException.prototype = Object.create.prototype

Function